name: Build
on:
  push: {}
  pull_request: {}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: wrapper

      - name: Build with Gradle 8.5
        run: gradle build

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: 'YggdrasilGateway/GatewayFrontend'
          path: 'frontend'

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: frontend
        env:
          CI: false
        run: |
          yarn install
          yarn run build

      - name: Build docker image - prepare
        run: gradle build buildDockerImage
        env:
          YG_FRONTEND_RESOURCES_LOCATION: frontend/build

      - name: Build docker image - build
        run: sleep 5 && docker build -t yggdrasilgateway components/gateway-bootstrap/build/tmp/buildDockerImage

      - name: Build docker image - save
        run: docker save yggdrasilgateway | gzip > yggdrasilgateway.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: yggdrasilgateway.tar.gz

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: '8.5'
