name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'


jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      withFrontend: false
      doUpload: false
  build-all:
    uses: ./.github/workflows/common-build.yml
    with:
      withFrontend: true
      doUpload: true
