name: Common-Build template

on:
  workflow_call:
    inputs:
      withFrontend:
        type: boolean
        default: true
      doUpload:
        type: boolean
        default: false


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: wrapper

      - name: Build with Gradle 8.5
        run: gradle build

      - name: Checkout frontend
        uses: actions/checkout@v4
        if: ${{ inputs.withFrontend }}
        with:
          repository: 'YggdrasilGateway/GatewayFrontend'
          path: 'frontend'

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        if: ${{ inputs.withFrontend }}
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Build frontend
        working-directory: frontend
        if: ${{ inputs.withFrontend }}
        env:
          CI: false
        run: |
          yarn install
          yarn run build:dev
          ls -lah build

      - name: Build docker image - prepare (with frontend)
        if: ${{ inputs.withFrontend }}
        run: gradle build buildDockerImage copyReleases -Pgateway.frontend.resources.location=frontend/build

      - name: Build docker image - prepare (without frontend)
        if: ${{ !inputs.withFrontend }}
        run: gradle build buildDockerImage copyReleases

      - name: Build docker image - build
        run: docker build -t yggdrasilgateway components/gateway-bootstrap/build/tmp/buildDockerImage

      - name: Build docker image - save
        if: ${{ inputs.doUpload }}
        run: docker save yggdrasilgateway | gzip > yggdrasilgateway.tar.gz

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.doUpload }}
        name: "Upload Docker Image"
        with:
          name: docker-image
          path: yggdrasilgateway.tar.gz

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.doUpload }}
        name: "Upload Distribution Zip"
        with:
          name: distribution-zip
          path: components/gateway-bootstrap/build/tmp/copyReleases/zip

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.doUpload }}
        name: "Upload Distribution Tar"
        with:
          name: distribution-tar
          path: components/gateway-bootstrap/build/tmp/copyReleases/tar
