name: Publish Snapshot

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'


jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      withFrontend: true
      doUpload: true

  publish_snapshot:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push'"
    permissions:
      contents: read
    needs:
      - build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{    vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Publish to DockerHub
        run: |
          docker load -i yggdrasilgateway.tar.gz
          docker tag yggdrasilgateway karlatemp/yggdrasil-gateway:nightly
          docker tag yggdrasilgateway karlatemp/yggdrasil-gateway:${{ github.sha }}
          docker push karlatemp/yggdrasil-gateway:${{ github.sha }}

      - name: Push nightly image
        if: "github.ref == 'refs/heads/main'"
        run: |
          docker push karlatemp/yggdrasil-gateway:nightly
