name: Release Tag

on:
  push:
    tags:
      - "*"


jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    with:
      withFrontend: true
      doUpload: true

  publish_snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{    vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          path: 'dist'
          name: docker-image

      - uses: actions/download-artifact@v4
        with:
          path: 'dist'
          name: distribution-zip

      - uses: actions/download-artifact@v4
        with:
          path: 'dist'
          name: distribution-tar


      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} -d --notes-from-tag dist/*

      - name: Publish to DockerHub
        run: |
          docker load -i yggdrasilgateway.tar.gz
          docker tag yggdrasilgateway karlatemp/yggdrasil-gateway:${{ github.ref_name }}
          docker push karlatemp/yggdrasil-gateway:${{ github.ref_name }}
